/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50717
Source Host           : localhost:3306
Source Database       : wechat-numberone

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2017-07-07 15:11:24
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for cbgentity
-- ----------------------------
DROP TABLE IF EXISTS `cbgentity`;
CREATE TABLE `cbgentity` (
  `id` varchar(36) NOT NULL,
  `addon_point` int(11) DEFAULT NULL,
  `all_caiguo` int(11) DEFAULT NULL,
  `appointed_roleid` varchar(255) DEFAULT NULL,
  `area_name` varchar(255) DEFAULT NULL,
  `badness` varchar(255) DEFAULT NULL,
  `baggage_extend_num` int(11) DEFAULT NULL,
  `bb_expt_fangyu` int(11) DEFAULT NULL,
  `bb_expt_fashu` int(11) DEFAULT NULL,
  `bb_expt_gongji` int(11) DEFAULT NULL,
  `bb_expt_kangfa` int(11) DEFAULT NULL,
  `bb_expt_total` int(11) DEFAULT NULL,
  `body_caiguo` int(11) DEFAULT NULL,
  `box_caiguo` int(11) DEFAULT NULL,
  `caifeng_score` int(11) DEFAULT NULL,
  `can_bargain` int(11) DEFAULT NULL,
  `cash` int(11) DEFAULT NULL,
  `changesch` int(11) DEFAULT NULL,
  `cheng_jiu` int(11) DEFAULT NULL,
  `clothes_num` int(11) DEFAULT NULL,
  `collect_num` int(11) DEFAULT NULL,
  `create_time` bigint(20) DEFAULT NULL,
  `dazao_score` int(11) DEFAULT NULL,
  `energy` int(11) DEFAULT NULL,
  `equip_count` int(11) DEFAULT NULL,
  `equip_name` varchar(255) DEFAULT NULL,
  `equip_type` int(11) DEFAULT NULL,
  `eval_price` int(11) DEFAULT NULL,
  `expire_time` bigint(20) DEFAULT NULL,
  `expt_fangyu` int(11) DEFAULT NULL,
  `expt_fashu` int(11) DEFAULT NULL,
  `expt_gongji` int(11) DEFAULT NULL,
  `expt_kangfa` int(11) DEFAULT NULL,
  `expt_lieshu` int(11) DEFAULT NULL,
  `expt_total` int(11) DEFAULT NULL,
  `fa_fang` int(11) DEFAULT NULL,
  `fa_shang` int(11) DEFAULT NULL,
  `fair_show_end_time` int(11) DEFAULT NULL,
  `fang_yu` int(11) DEFAULT NULL,
  `fangwu_level` int(11) DEFAULT NULL,
  `full_life_skill_num` int(11) DEFAULT NULL,
  `game_ordersn` varchar(255) DEFAULT NULL,
  `game_serverid` varchar(255) DEFAULT NULL,
  `growup_pet_num` int(11) DEFAULT NULL,
  `has_community` int(11) DEFAULT NULL,
  `hero_score` int(11) DEFAULT NULL,
  `hp` int(11) DEFAULT NULL,
  `icon` int(11) DEFAULT NULL,
  `id2` int(11) DEFAULT NULL,
  `is_gold_id` int(11) DEFAULT NULL,
  `is_item_exist` int(11) DEFAULT NULL,
  `is_married` int(11) DEFAULT NULL,
  `is_niceid` int(11) DEFAULT NULL,
  `is_tongpao` int(11) DEFAULT NULL,
  `ji_yuan_point` int(11) DEFAULT NULL,
  `jiyuan_and_addpoint` int(11) DEFAULT NULL,
  `kindid` int(11) DEFAULT NULL,
  `learn_cash` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `lin_shi_fu` int(11) DEFAULT NULL,
  `ling_li` int(11) DEFAULT NULL,
  `lingshi_max_duanzao_level` int(11) DEFAULT NULL,
  `lingshi_max_level` int(11) DEFAULT NULL,
  `lingshi_min_duanzao_level` int(11) DEFAULT NULL,
  `lingshi_min_level` int(11) DEFAULT NULL,
  `max_equip_duan_zao` int(11) DEFAULT NULL,
  `max_expt_fangyu` int(11) DEFAULT NULL,
  `max_expt_fashu` int(11) DEFAULT NULL,
  `max_expt_gongji` int(11) DEFAULT NULL,
  `max_expt_kangfa` int(11) DEFAULT NULL,
  `max_necklace_init_wakan` int(11) DEFAULT NULL,
  `max_necklace_ling_li` int(11) DEFAULT NULL,
  `max_weapon_damage` int(11) DEFAULT NULL,
  `max_weapon_init_damage` int(11) DEFAULT NULL,
  `max_weapon_init_damage_raw` int(11) DEFAULT NULL,
  `max_weapon_shang_hai` int(11) DEFAULT NULL,
  `ming_zhong` int(11) DEFAULT NULL,
  `muchang_level` int(11) DEFAULT NULL,
  `nickname` varchar(255) DEFAULT NULL,
  `nosale_xr_num` int(11) DEFAULT NULL,
  `org_offer` int(11) DEFAULT NULL,
  `pass_fair_show` int(11) DEFAULT NULL,
  `pet_ex_num` int(11) DEFAULT NULL,
  `pet_extend_num` int(11) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `pride` int(11) DEFAULT NULL,
  `qian_neng_guo` int(11) DEFAULT NULL,
  `qian_yuan_dan` int(11) DEFAULT NULL,
  `race` int(11) DEFAULT NULL,
  `rider_exgrow_full_num` int(11) DEFAULT NULL,
  `roleid` varchar(255) DEFAULT NULL,
  `school` int(11) DEFAULT NULL,
  `school_offer` int(11) DEFAULT NULL,
  `school_skill_1` int(11) DEFAULT NULL,
  `school_skill_2` int(11) DEFAULT NULL,
  `school_skill_3` int(11) DEFAULT NULL,
  `school_skill_4` int(11) DEFAULT NULL,
  `school_skill_5` int(11) DEFAULT NULL,
  `school_skill_6` int(11) DEFAULT NULL,
  `school_skill_7` int(11) DEFAULT NULL,
  `school_skill_idx1` int(11) DEFAULT NULL,
  `school_skill_idx2` int(11) DEFAULT NULL,
  `school_skill_idx3` int(11) DEFAULT NULL,
  `school_skill_idx4` int(11) DEFAULT NULL,
  `school_skill_idx5` int(11) DEFAULT NULL,
  `school_skill_idx6` int(11) DEFAULT NULL,
  `school_skill_idx7` int(11) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `selling_time` int(11) DEFAULT NULL,
  `server_name` varchar(255) DEFAULT NULL,
  `serverid` int(11) DEFAULT NULL,
  `sew_skill` int(11) DEFAULT NULL,
  `shang_hai` int(11) DEFAULT NULL,
  `sheng_yu_ling_you` int(11) DEFAULT NULL,
  `skill_anqi` int(11) DEFAULT NULL,
  `skill_baoshi` int(11) DEFAULT NULL,
  `skill_bianhua` int(11) DEFAULT NULL,
  `skill_caifeng` int(11) DEFAULT NULL,
  `skill_cuiling` int(11) DEFAULT NULL,
  `skill_danyuan` int(11) DEFAULT NULL,
  `skill_dazao` int(11) DEFAULT NULL,
  `skill_dazuo` int(11) DEFAULT NULL,
  `skill_drive_pet` int(11) DEFAULT NULL,
  `skill_gudong` int(11) DEFAULT NULL,
  `skill_huoyan` int(11) DEFAULT NULL,
  `skill_jianshen` int(11) DEFAULT NULL,
  `skill_jianzhu` int(11) DEFAULT NULL,
  `skill_lianjin` int(11) DEFAULT NULL,
  `skill_lingshi` int(11) DEFAULT NULL,
  `skill_miaoshou` int(11) DEFAULT NULL,
  `skill_ming_xiang` int(11) DEFAULT NULL,
  `skill_pengren` int(11) DEFAULT NULL,
  `skill_qiang_shen` int(11) DEFAULT NULL,
  `skill_qiang_zhuang` int(11) DEFAULT NULL,
  `skill_qiaojiang` int(11) DEFAULT NULL,
  `skill_qimen` int(11) DEFAULT NULL,
  `skill_ronglian` int(11) DEFAULT NULL,
  `skill_shensu` int(11) DEFAULT NULL,
  `skill_taoli` int(11) DEFAULT NULL,
  `skill_tiaoxi` int(11) DEFAULT NULL,
  `skill_xianling` int(11) DEFAULT NULL,
  `skill_yangsheng` int(11) DEFAULT NULL,
  `skill_zhongyao` int(11) DEFAULT NULL,
  `skill_zhuibu` int(11) DEFAULT NULL,
  `smith_skill` int(11) DEFAULT NULL,
  `speed` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `sum_exp` int(11) DEFAULT NULL,
  `sword_score` int(11) DEFAULT NULL,
  `time_left` varchar(255) DEFAULT NULL,
  `tingyuan_level` int(11) DEFAULT NULL,
  `upexp` bigint(20) DEFAULT NULL,
  `xian_yu` int(11) DEFAULT NULL,
  `xiangrui_num` int(11) DEFAULT NULL,
  `zhuang_zhi` int(11) DEFAULT NULL,
  `getTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `xingjiabi` int(11) DEFAULT NULL,
  `cbgurl` varchar(1255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `r` (`roleid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
